[package]
name = "termi-jump"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
crossterm = "0.27"
tensorflow = { git = "https://github.com/tensorflow/rust" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
